### PR TITLE
Feature 1

### PR DESCRIPTION
**Pull request by Sick-Carlito**
Added a user sign up functionality to enable a user to sign up and log in to create a post. Users are supposed to see the author of the posts only when they are signed in.

### CODE REVIEW

**Review by ebukaume — CHANGES_REQUESTED** [review]
Hi @Sick-Carlito :wave: 

This project is supposed to be collaborative. Any reason you are running solo on it? 

Now to the project, nice job so far. However, there are issues we need to take care of before moving forward.

* [ ] User can sign in ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) - **I am not able to sign in nor sign up**
* [ ] As a signed-in user you can create new post ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_post_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) - **Because I couldn't sign in, I couldn't create posts**
* [ ] As a signed-in user you can see post's author ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) - **Same as above...**
* [ ] User can sign_out ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) - **Same issue dependent on sign in...**
* [ ] As a guest you can see only post's text ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) - **Likewise...**

**Please fix this so we can go ahead and review the other parts of the app. I recommend you go through the project requirements and check all the boxes before submitting another review.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by Sick-Carlito** [comment]
Hello Ebuka, thanks for your feedback. First, I was authorised to work alone by the student success team since I haven't been paired yet 😊

About the project, the instructions did not require us to use any sign up functionality. As stated in the readme file, you can create a new user from the console [ this acts as the sign up functionality] and use the stored information to sign in. I can only add the sign up functionality just for extra credits but it wasn't in the instructions given. If you follow the instructions on my readme file, it will work just fine 😃.

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

This assignment consists of using the bcrypt gem to have a first approach at authentication in rails. you are supposed to build an application that allows users to create posts and the authors of the posts are displayed only if as a user is logged in.

- The views should be updated implementing the functionalities requested in the previous review from the views and not only the console.

- Please add a short description of the changes you've made to the pull request.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Review by Ispirett — APPROVED** [review]
## Status Approved 
Great job with this project and changes made :+1:  @Sick-Carlito 

Couple of things to note!
- [ ] consider after user signs up to automatically log them in.
- [ ] It will  be nicer to have the sign up option as  as a link
- [ ] It will be nicer to have the sign in form only use  name/password or email/password to sgin in.

**Comment by Sick-Carlito** [comment]
Thanks, I will probably work on the extras later.

**Pull request merged**
